const torneoDeFutbol5 = { 
    name: 'LIB',
    description: 'Liga Inter Barrial, con 10 equipos enfrentandose los fines de semana desde Agosto 2020',
    location: 'Ciudad de Tafi Viejo, Tucumán',
    duration: '9 semanas',
    teams: [{
        name: 'Loma Linda FC',
        stadium: 'La Diagonal',
        t_shirtColor: 'verde, blanco y negro',
        trophys: '5',
        players: [{
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Marcos',
                lastName: 'Vallejos',
                address: 'Loma Linda Mza Z Lote 3',
                e_mail: 'macosV@hotmail.com',
                phoneNumber: '381-4562132',
                id: 'DNI 3084518',
                age: '34',
                height_m: '1.70',
                weight_kg: '79',
                position: 'defensor',
                profession: 'Abogado',
                hobby: 'tenis',
            } , {
                name: 'Juan Carlos',
                lastName: 'Lezana',
                address: 'Loma Linda Mza H Lote 5',
                e_mail: 'lolole@hotmail.com',
                phoneNumber: '381-3265148',
                id: 'DNI 32719450',
                age: '32',
                height_m: '1.83',
                weight_kg: '87',
                position: 'arquero',
                profession: 'Asegurador',
                hobby: 'ciclismo',
            } , {
                name: 'Ennio',
                lastName: 'Sanchez',
                address: 'Loma Linda Mza I Lote 12',
                e_mail: 'ennio_25@hotmail.com',
                phoneNumber: '381-5114873',
                id: 'DNI 33985412',
                age: '33',
                height_m: '1.77',
                weight_kg: '98',
                position: 'mediocampista',
                profession: 'Chef',
                hobby: 'animación',
            } , {
                name: 'Matias',
                lastName: 'Valladares',
                address: 'Loma Linda Mza L Lote 3',
                e_mail: 'mvalladares@hotmail.com',
                phoneNumber: '381-5635249',
                id: 'DNI 33721566',
                age: '33',
                height_m: '1.81',
                weight_kg: '83',
                position: 'delantero',
                profession: 'Profesor Ed. Física',
                hobby: 'paddle',
            } , {
                name: 'Diego',
                lastName: 'Divi',
                address: 'Loma Linda Mza H Lote 23',
                e_mail: 'diegod31@hotmail.com',
                phoneNumber: '381-5213421',
                id: 'DNI 29715822',
                age: '37',
                height_m: '1.74',
                weight_kg: '75',
                position: 'delantero',
                profession: 'Abogado',
                hobby: 'cocinar',
            } , {
                name: 'Maximiliano',
                lastName: 'Ledda',
                address: 'Loma Linda Mza J Lote 17',
                e_mail: 'ledatanque@hotmail.com',
                phoneNumber: 381-5385147,
                id: 30725413,
                age: 35,
                height_m: 1.62,
                weight_kg: 83,
                position: 'mediocampista',
                profession: 'Comerciante',
                hobby: 'barman',
            },
            {
                name: 'Matías',
                lastName: 'Aybar',
                address: 'Loma Linda Mza J Lote 17',
                e_mail: 'ledatanque@hotmail.com',
                phoneNumber: 381-5385147,
                id: 30725413,
                age: 35,
                height_m: 1.62,
                weight_kg: 83,
                position: 'mediocampista',
                profession: 'Comerciante',
                hobby: 'barman',
            }]
    } , {
        name: 'Labradores FC',
        stadium: 'La Diagonal',
        t_shirtColor: 'gris',
        trophys: '2',
        players: [{
            name: 'Matias',
            lastName: 'Lopez Klyver',
            address: 'Loma Linda Mza Ai Lote 10',
            e_mail: 'lopezk_matias@hotmail.com',
            phoneNumber: '381-5452112',
            id: 'DNI 30920131',
            age: '35',
            height_m: '1.65',
            weight_kg: '90',
            position: 'defensor',
            profession: 'Ingeniero - Programador',
            hobby: 'ping-pong',
        } , {
            name: 'Marcos',
            lastName: 'Vallejos',
            address: 'Loma Linda Mza Z Lote 3',
            e_mail: 'macosV@hotmail.com',
            phoneNumber: '381-4562132',
            id: 'DNI 3084518',
            age: '34',
            height_m: '1.70',
            weight_kg: '79',
            position: 'defensor',
            profession: 'Abogado',
            hobby: 'tenis',
        } , {
            name: 'Juan Carlos',
            lastName: 'Lezana',
            address: 'Loma Linda Mza H Lote 5',
            e_mail: 'lolole@hotmail.com',
            phoneNumber: '381-3265148',
            id: 'DNI 32719450',
            age: '32',
            height_m: '1.83',
            weight_kg: '87',
            position: 'arquero',
            profession: 'Asegurador',
            hobby: 'ciclismo',
        } , {
            name: 'Ennio',
            lastName: 'Sanchez',
            address: 'Loma Linda Mza I Lote 12',
            e_mail: 'ennio_25@hotmail.com',
            phoneNumber: '381-5114873',
            id: 'DNI 33985412',
            age: '33',
            height_m: '1.77',
            weight_kg: '98',
            position: 'mediocampista',
            profession: 'Chef',
            hobby: 'animación',
        } , {
            name: 'Matias',
            lastName: 'Valladares',
            address: 'Loma Linda Mza L Lote 3',
            e_mail: 'mvalladares@hotmail.com',
            phoneNumber: '381-5635249',
            id: 'DNI 33721566',
            age: '33',
            height_m: '1.81',
            weight_kg: '83',
            position: 'delantero',
            profession: 'Profesor Ed. Física',
            hobby: 'paddle',
        } , {
            name: 'Diego',
            lastName: 'Divi',
            address: 'Loma Linda Mza H Lote 23',
            e_mail: 'diegod31@hotmail.com',
            phoneNumber: '381-5213421',
            id: 'DNI 29715822',
            age: '37',
            height_m: '1.74',
            weight_kg: '75',
            position: 'delantero',
            profession: 'Abogado',
            hobby: 'cocinar',
        } , {
            name: 'Maximiliano',
            lastName: 'Ledda',
            address: 'Loma Linda Mza J Lote 17',
            e_mail: 'ledatanque@hotmail.com',
            phoneNumber: '381-5385147',
            id: 'DNI 30725413',
            age: '35',
            height_m: '1.62',
            weight_kg: '83',
            position: 'mediocampista',
            profession: 'Comerciante',
            hobby: 'barman',
        }]
    } , {
        name: 'Loma Linda FC',
        stadium: 'La Diagonal',
        t_shirtColor: 'verde, blanco y negro',
        trophys: '5',
        players: [{
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            }]

    } , {
        name: 'Loma Linda FC',
        stadium: 'La Diagonal',
        t_shirtColor: 'verde, blanco y negro',
        trophys: '5',
        players: [{
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            }]
    } , {
        name: 'Loma Linda FC',
        stadium: 'La Diagonal',
        t_shirtColor: 'verde, blanco y negro',
        trophys: '5',
        players: [{
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            }]
    } , {
        name: 'Loma Linda FC',
        stadium: 'La Diagonal',
        t_shirtColor: 'verde, blanco y negro',
        trophys: '5',
        players: [{
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            }]
    } , {
        name: 'Loma Linda FC',
        stadium: 'La Diagonal',
        t_shirtColor: 'verde, blanco y negro',
        trophys: '5',
        players: [{
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            }]
    } , {
        name: 'Loma Linda FC',
        stadium: 'La Diagonal',
        t_shirtColor: 'verde, blanco y negro',
        trophys: '5',
        players: [{
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            }]
    } , {
        name: 'Loma Linda FC',
        stadium: 'La Diagonal',
        t_shirtColor: 'verde, blanco y negro',
        trophys: '5',
        players: [{
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            }]
    } , {
        name: 'Loma Linda FC',
        stadium: 'La Diagonal',
        t_shirtColor: 'verde, blanco y negro',
        trophys: '5',
        players: [{
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            } , {
                name: 'Matias',
                lastName: 'Lopez Klyver',
                address: 'Loma Linda Mza Ai Lote 10',
                e_mail: 'lopezk_matias@hotmail.com',
                phoneNumber: '381-5452112',
                id: 'DNI 30920131',
                age: '35',
                height_m: '1.65',
                weight_kg: '90',
                position: 'defensor',
                profession: 'Ingeniero - Programador',
                hobby: 'ping-pong',
            }]
    }]
};

const app = document.getElementById('app');

const section1 = document.createElement('section');
section1.id = 'primary-info';
section1.className = 'jumbotron';
const title = document.createElement('h1');
title.innerText = torneoDeFutbol5.name;
const description = document.createElement('p');
description.innerText = torneoDeFutbol5.description;
const description2 = document.createElement('p');
description2.className = 'small text-muted';
description2.innerText = `${torneoDeFutbol5.location} - ${torneoDeFutbol5.duration}`;

section1.appendChild(title);
section1.appendChild(description);
section1.appendChild(description2);

app.appendChild(section1);

const teams = torneoDeFutbol5.teams;
const r1 = document.createElement('div');
r1.className = 'row mt-2 mb-2';
for (let i = 0; i < teams.length; i++) {
    const players = teams[i].players;
    const c1 = document.createElement('div');
    const title1 = document.createElement('h3');
    const p1 = document.createElement('p');
    const p2 = document.createElement('p');
    const p3 = document.createElement('p');
    const btn1 = document.createElement('button');
    btn1.innerText = 'Ver jugadores';
    btn1.type = 'button';
    btn1.className = 'btn btn-primary btn-sm mb-4';
    title1.innerText = teams[i].name;
    p1.innerHTML = `* <b>Stadium</b>: ${teams[i].stadium}`;
    p2.innerHTML = `* <b>t_shirtColor</b>: ${teams[i].t_shirtColor}`;
    p3.innerHTML = `* <b>trophys</b>: ${teams[i].trophys}`;
    c1.className = 'col-md-4 card';
    c1.appendChild(title1);
    c1.appendChild(p1);
    c1.appendChild(p2);
    c1.appendChild(p3);
    c1.appendChild(btn1);
    const p4 = document.createElement('ol');
    for (let j = 0; j < players.length; j++) {
        const sp1 = document.createElement('li');
        sp1.innerText = `${players[j].name} ${players[j].lastName}, `;
        p4.appendChild(sp1);
    }
    c1.appendChild(p4);
    r1.appendChild(c1);
}

app.appendChild(r1);

